name: ZIP and upload to Google Cloud Storage

on:
  push:
    branches:
      - main
      - dev

env:
  GCP_PROJECTID: creditriskmlops
  DEV_GCS: gs://creditriskmlops-mlmodelretrain-dev
  MAIN_GCS: gs://creditriskmlops-mlmodelretrain-prd

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: Upload repos code to GitHub Actions runner
      uses: actions/checkout@v2
    
    - name: Zip repos code 
      run: zip -r mlmodelretrain.zip .

    - name: Echo dir
      run: dir .
      
    - name: Auth to GCP
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Upload ZIP to GCS
      uses: google-github-actions/upload-cloud-storage@v2
      with:
        path: './mlmodelretrain.zip'
        destination: ${{ env.DEV_GCS }}
