name: ZIP and upload to Google Cloud Storage

on:
  push:
    branches:
      - main
      - dev

env:
  GCP_PROJECTID: creditriskmlops
  DEV_GCS: gs://creditriskmlops-mlmodelretrain-dev
  MAIN_GCS: gs://creditriskmlops-mlmodelretrain-prd

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: Upload repos code to GitHub Actions runner
      uses: actions/checkout@v2
    
    - name: Zip repos code 
      run: zip -r mlmodelretrain.zip .
    
    - name: Auth to GCP
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GCP_PROJECTID }}

    - name: Config Docker
      run: |
        gcloud auth configure-docker
  
    - name: Upload to dev Google Cloud Storage Bucket
      if: github.ref == 'refs/heads/dev'
      run: |
        gsutil cp mlmodelretrain.zip $DEV_GCS/mlmodelretrain.zip

    - name: Upload to prd Google Cloud Storage Bucket
      if: github.ref == 'refs/heads/main'
      run: |
        gsutil cp mlmodelretrain.zip $MAIN_GCS/mlmodelretrain.zip
